# Generated by Django 5.1.1 on 2024-12-28 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='ArchiveHomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archived Homepage Image',
                'verbose_name_plural': 'Archived Homepage Images',
                'db_table': 'archive_homepage_images',
            },
        ),
        migrations.CreateModel(
            name='ArchiveHrAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('password_status', models.CharField(max_length=45)),
                ('hraccount_status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Archive HR Account',
                'verbose_name_plural': 'Archive HR Accounts',
                'db_table': 'archive_hraccount',
            },
        ),
        migrations.CreateModel(
            name='ArchiveReservation',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room_type', models.CharField(max_length=255)),
                ('typeofbooking', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('cancelreason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('settlements', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Archive Reservation',
                'verbose_name_plural': 'Archive Reservations',
                'db_table': 'archive_reservation',
            },
        ),
        migrations.CreateModel(
            name='ArchiveRoomPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Archive Room Promotion',
                'verbose_name_plural': 'Archive Room Promotions',
                'db_table': 'archive_room_promotions',
            },
        ),
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Image',
                'verbose_name_plural': 'Homepage Images',
                'db_table': 'homepage_images',
            },
        ),
        migrations.CreateModel(
            name='HrAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('password_status', models.CharField(max_length=45)),
                ('hraccount_status', models.CharField(max_length=45)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'HR Account',
                'verbose_name_plural': 'HR Accounts',
                'db_table': 'hraccount',
            },
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room_type', models.CharField(max_length=255)),
                ('typeofbooking', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('cancelreason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('settlements', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Room Promotion',
                'verbose_name_plural': 'Room Promotions',
                'db_table': 'room_promotions',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'constraints': [models.UniqueConstraint(fields=('email', 'username'), name='unique_account')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Archive Account',
                'verbose_name_plural': 'Archive Accounts',
                'db_table': 'archive_accounts',
                'constraints': [models.UniqueConstraint(fields=('email', 'username'), name='unique_archive_account')],
            },
        ),
    ]
