# Generated by Django 5.1.1 on 2025-01-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSXHotel', '0002_alter_hraccount_username_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
