# Generated by Django 5.1.1 on 2025-01-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSXHotel', '0004_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='JSXHotel.account'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='otp',
            table='otps',
        ),
    ]
