# Generated by Django 5.1.1 on 2025-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSXHotel', '0005_remove_otp_user_otp_account_alter_otp_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Blocklist',
                'verbose_name_plural': 'Blocklists',
                'db_table': 'blocklist',
            },
        ),
    ]
