# Generated by Django 5.1.1 on 2025-01-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSXHotel', '0006_blocklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocklist',
            old_name='address',
            new_name='roomtype',
        ),
    ]
