# Generated by Django 5.1.1 on 2025-01-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSXHotel', '0007_rename_address_blocklist_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocklist',
            name='roomtype',
        ),
    ]
