# Generated by Django 5.1.1 on 2025-01-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSXHotel', '0008_remove_blocklist_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='otp',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JSXHotel.account'),
        ),
        migrations.AlterModelTable(
            name='otp',
            table=None,
        ),
    ]
