# Generated by Django 5.1.1 on 2025-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSXHotel', '0009_otp_email_alter_otp_account_alter_otp_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompromotion',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
