# Generated by Django 5.1.1 on 2025-01-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSXHotel', '0010_roompromotion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveroompromotion',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
